# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0002_auto_20150606_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430 \u0442\u043e\u0432\u0430\u0440\u0430')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u0438')),
                ('photo_technic', filer.fields.image.FilerImageField(blank=True, help_text='Optional. Please supply a photo of this main member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_technic', to='filer.Image', verbose_name='\u0424\u043e\u0442\u043e\u0433\u0440\u0430\u0444\u0438\u044f')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.CreateModel(
            name='Technic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0442\u0435\u0445\u043d\u0438\u043a\u0438')),
                ('description', redactor.fields.RedactorField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('count', models.BigIntegerField(verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0435\u0434\u0435\u043d\u0438\u0446')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='\u0421\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c \u0435\u0434\u0438\u043d\u0438\u0446\u044b, \u0440\u0443\u0431.')),
                ('shou', models.BooleanField(default=True, verbose_name='\u041e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c \u043d\u0430 \u0441\u0430\u0439\u0442\u0435')),
                ('first_order', models.BooleanField(default=False, verbose_name='\u041f\u0435\u0440\u0432\u044b\u0435 \u0432 \u0441\u043f\u0438\u0441\u043a\u0435')),
                ('pub_date', models.DateTimeField(verbose_name='\u0421\u0440\u043e\u043a \u0440\u0430\u0437\u043c\u0435\u0449\u0435\u043d\u0438\u044f \u0432 \u0434\u043d\u044f\u0445')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_technic', to='technic.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_technic_producer', to='technic.Producer', verbose_name='\u041f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='spare',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_technic', to='technic.Technic', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430'),
        ),
    ]
